# This TOML structure will be rendered to JSON via a Handlebars template

# == connectors
# rendered as an array of connector configs, so each should get the TOML table
# of [["connectors"]]

# - Sample Slack connector
#[["connectors"]]
#type = "slack"
#username = "Linkbot"
#icon_url = "http://icons.iconarchive.com/icons/pixelpirate/futurama/256/Hedonism-Bot-icon.png"
#token = "gottaprovidethis"
#periodic = true

# == plugins
# Rendered as a hash-of-hashes-like structure that varies from plugin to plugin
[plugins]
# - sample hubstat
#[plugins.hubstat]
#room = "wheredoyouwantmetopost?"

# - sample weather
#[plugins.weather]
#key = "gottaprovidethistoo"
#default-zip = "21224"
#icons = true
