source "http://rubygems.org"

gem "sanitize"
gem "htmlentities"
gem "json"
gem "sqlite3"
gem "hpricot"
gem "activesupport"
gem "twss"
gem "httparty"
gem "em-http-request"
gem "eventmachine"
gem "rack"
gem "thin"
gem "sinatra"
gem "xmpp4r", :git => "git://github.com/hoxworth/xmpp4r.git"
gem "imagesize"
gem "octokit", "2.0.0.rc2"
gem "tzinfo"
gem "em-irc"

group :dev do
  gem "byebug"
  gem "pry"
  gem "rspec"
end
