source "http://rubygems.org"
source "http://gemcutter.org"

gem "sanitize"
gem "htmlentities"
gem "json"
gem "sqlite3"
gem "hpricot"
gem "activesupport"
gem "twss"
gem "httparty"
gem "twitter-stream"
gem "eventmachine"