class Handey < Linkbot::Plugin

  def initialize
    register :regex => /!deepthought/
    help "!deepthought - return a deep thought"
  end

  def on_message(message, matches)
    QUOTES.sample + " - Jack Handey"
  end

  QUOTES = ["Before criticizing someone, walk a mile in their shoes. Then when you do criticize them, you will be a mile away and have their shoes.",
    "I can picture in my mind a world without war, a world without hate. And I can picture us attacking that world, because they'd never expect it.",
    "I don't think I'm alone when I say I'd like to see more and more planets fall under the ruthless domination of our solar system.",
    "A good way to threaten somebody is to light a stick of dynamite. Then you call the guy and hold the burning fuse up to the phone. \"Hear that?\" you say. \"That's dynamite, baby.\"",
    "A man doesn't automatically get my respect. He has to get down in the dirt and beg for it.",
    "As the light changed from red to green to yellow and back to red again, I sat there thinking about life. Was it nothing more than a bunch of honking and yelling? Sometimes it seemed that way.",
    "I hope that someday we will be able to put away our fears and prejudices and just laugh at people.",
    "I hope that after I die, people will say of me: ``That guy sure owed me a lot of money.''",
    "It's too bad that whole families have to be torn apart by something as simple as wild dogs.",
    "If God dwells inside us, like some people say, I sure hope He likes enchiladas, because that's what He's getting!",
    "When you're riding in a time machine way far into the future, don't stick your elbow out the window, or it'll turn into a fossil.",
    "Children need encouragement. So if a kid gets an answer right, tell him it was a lucky guess. That way, he develops a good, lucky feeling.",
    "I think people tend to forget that trees are living creatures. They're sort of like dogs. Huge, quiet, motionless dogs, with bark instead of fur.",
    "Perhaps, if I am very lucky, the feeble efforts of my lifetime will someday be noticed, and maybe, in some small way, they will be acknowledged as the greatest works of genius ever created by Man.",
    "If your kid makes one of those little homemade guitars out of a cigar box and rubber bands, don't let him just play it once or twice and then throw it away. Make him practice on it, every day, for about three hours a day. Later, he'll thank you.",
    "I believe in making the world safe for our children, but not our children's children, because I don't think children should be having sex.",
    "Anytime I see something screech across a room and latch onto someone's neck, and the guy screams and tries to get it off, I have to laugh, because what IS that thing?!",
    "Just because swans mate for life, I don't think it's that big of a deal. First of all, if you're a swan, you're probably not going to find a swan that looks that much better than the one you've got, so why not mate for life?",
    "If you're a cowboy, and you're dragging a guy behind your horse, I bet it would really make you mad if you looked back and the guy was reading a magazine.",
    "It's easy to sit there and say you'd like to have more money. And I guess thats what I like about it. It's easy. Just sitting there, rocking back and forth, wanting that money.",
    "If I was the head of a country that lost a war, and I had to sign a peace treaty, just as I was signing I'd glance over the treaty and then suddenly act surprised. \"Wait a minute! I thought WE won!\"",
    "Is there anything more beautiful than a beautiful, beautiful flamingo, flying across in front of a beautiful sunset? And he's carrying a beautiful rose in his beak, and also he's carrying a very beautiful painting with his feet. And also, you're drunk.",
    "I don't pretend to have all the answers. I don't pretend to even know what the questions are. Hey, where am I? ",
    "I think that a hat which has a little cannon that fires and then goes back inside the hat is at least a decade away. ",
    "If you saw two guys named Hambone and Flippy, which one would you think liked dolphins the most? I'd say Flippy, wouldn't you? You'd be wrong though. It's Hambone. ",
    "Instead of a trap door, what about a trap window? The guy looks out it, and if he leans too far, he falls out. Wait. I guess that's like a regular window.",
    "Maybe in order to understand mankind, we have to look at the word it Mankind. Basically, it's made up of two separate words - \"mank\" and \"ind\". What do these words mean? It's a mystery, and that's why so is mankind.",
    "Instead of a Seeing Eye dog, what about a gun? It's cheaper than a dog, plus if you walk around shooting all the time people are going to get out of the way. Cars, too!",
    "Dad always thought laughter was the best medicine, which I guess is why several of us died of tuberculosis. ",
    "Instead of studying for finals, what about just going to the Bahamas and catching some rays? Maybe you'll flunk, but you might have flunked anyway; that's my point.",
    "I have to laugh when I think of the first cigar, because it was probably just a bunch of rolled-up tobacco leaves.",
    "If you're ever shipwrecked on a tropical island and you don't know how to speak the natives' language, just say \"Poppy-oomy.\" I bet it means something.",
    "Too bad Lassie didn't know how to ice skate, because then if she was in Holland on vacation in winter and someone said \"Lassie, go skate for help,\" she could do it.",
    "If you want to be the most popular person in your class, whenever the professor pauses in his lecture, just let out a big snort and say \"How do you figger that!\" real loud. Then lean back and sort of smirk.",
    "I think my new thing will be to try to be a real happy guy. I'll just walk around being real happy until some jerk says something stupid to me.",
    "I think college administrators should encourage students to urinate on walls and bushes, because then when students from another college come sniffing around, they'll know this is someone else's territory.",
    "He was the kind of man who was not ashamed to show affection. I guess that's what I hated about him.",
    "If they have moving sidewalks in the future, when you get on them, I think you should have to assume sort of a walking shape so as not to frighten the dogs.",
    "Whenever I hear the sparrow chirping, watch the woodpecker chirp, catch a chirping trout, or listen to the sad howl of the chirp rat, I think: Oh boy! I'm going insane again.",
    "It's fascinating to think that all around us there's an invisible world we can't even see. I'm speaking, of course, of the World of the Invisible Scary Skeletons.",
    "The land that had nourished him and had borne him fruit now turned against him and called him a fruit. Man, I hate land like that.",
    "I bet it was pretty hard to pick up girls if you had the Black Death.",
    "Love can sweep you off your feet and carry you along in a way you've never known before. But the ride always ends, and you end up feeling lonely and bitter. Wait. It's not love I'm describing. I'm thinking of a monorail.",
    "Sometimes life seems like a dream, especially when I look down and see that I forgot to put on my pants.",
    "I think the monkeys at the zoo should have to wear sunglasses so they can't hypnotize you.",
    "The difference between a man and a boy is, a boy wants to grow up to be a fireman, but a man wants to grow up to be a giant monster fireman.",
    "I guess more bad things have been done in the name of progress than any other. I myself have been guilty of this. When I was a teen-ager, I stole a car and drove it out into the desert and set it on fire. When the police showed up, I just shrugged and said, \"Hey, progress.\" Boy, did I have a lot to learn.",
    "It's amazing to me that one of the world's most feared diseases would be carried by one of the world's smallest animals: the real tiny dog.",
    "When the chairman introduced the guest speaker as a former illegal alien, I got up from my chair and yelled, \"What's the matter, no jobs on Mars?\" When no one laughed, I was real embarrassed. I don't think people should make you feel that way.",
    "Marta was watching the football game with me when she said, \"You know, most of these sports are based on the idea of one group protecting its territory from invasion by another group.\" \"Yeah,\" I said, trying not to laugh. Girls are funny.",
    "I hope, when they die, cartoon characters have to answer for their sins.",
    "Here's a good trick: Get a job as a judge at the Olympics. Then, if some guy sets a world record, pretend that you didn't see it and go, \"Okay, is everybody ready to start now?\"",
    "Any man, in the right situation, is capable of murder. But not any man is capable of being a good camper. So, murder and camping are not as similar as you might think.",
    "Laugh, clown, laugh. This is what I tell myself whenever I dress up like Bozo.",
    "In some places it's known as a tornado. In others, a cyclone. And in still others, the Idiot's Merry-go-round. But around here they'll always be known as screw-boys.",
    "Folks still remember the day ole Bob Riley came bouncing down that dirt road in his pickup. Pretty soon, it was bouncing higher and higher. The tires popped, and the shocks broke, but that truck kept bouncing. Some say it bounced clean over the moon, but whoever says that is a goddamn liar.",
    "Tonight, when we were eating dinner, Marta said something that really knocked me for a loop. She said, \"I love carrots.\" \"Good,\" I said as I gritted my teeth real hard. \"Then maybe you and carrots would like to go into the bedroom and have sex!\" They didn't, but maybe they will sometime, and I can watch.",
    "I hate it when people say somebody has a \"speech impediment\", even if he does, because it could hurt his feelings. So instead, I call it a \"speech improvement\", and I go up to the guy and say, \"Hey, Bob, I like your speech improvement.\" I think this makes him feel better.",
    "Anybody who has an identity problem had better wise up and get with the program!",
    "I think there should be something in science called the \"reindeer effect.\" I don't know what it would be, but I think it'd be good to hear someone say, \"Gentlemen, what we have here is a terrifying example of the reindeer effect.\"",
    "If I had a mine shaft, I don't think I would just abandon it. There's got to be a better way.",
    "If Alien was my friend, I'd like to be with him when he went to the dentist. When they started drilling, he'd probably go nuts and start eating everybody. That Alien!",
    "I bet it's hard to break farmers of the old superstitions like \"Tornado got Old Yeller, stay in the cellar.\"",
    "I bet when the neanderthal kids would make a snowman, someone would always end up saying, \"Don't forget the thick, heavy brows.\" Then they would all get embarrassed because they remembered they had the big hunky brows too, and they'd get mad and eat the snowman.",
    "I'd like to be buried Indian-style, where they put you up on a high rack, above the ground. That way, you could get hit by meteorites and not even feel it.",
    "Why do people in ship mutinies always ask for \"better treatment\"? I'd ask for a pinball machine, because with all that rocking back and forth you'd probably be able to get a lot of free games.",
    "I guess we were all guilty, in a way. We all shot him, we all skinned him, and we all got a complimentary bumper sticker that said, \"I helped skin Bob.\"",
    "I bet for an Indian, shooting an old fat pioneer woman in the back with an arrow, and she fires her shotgun into the ground as she falls over, is like the top thing you can do.",
    "To me, it's always a good idea to always carry two sacks of something when you walk around. That way, if anybody says, \"Hey, can you give me a hand?,\" you can say, \"Sorry, got these sacks.\" ",
    "If I ever get real rich, I hope I'm not real mean to poor people, like I am now.",
    "Whenever you read a good book, it's like the author is right there, in the room, talking to you, which is why I don't like to read good books.",
    "I hope some animal never bores a hole in my head and lays its eggs in my brain, because later you might think you're having a good idea but it's just eggs hatching.",
    "If you go flying back through time, and you see somebody else flying forward into the future, it's probably best to avoid eye contact.",
    "You know one thing that will really make a woman mad? Just run up and kick her in the butt. (P.S. This also works with men.)",
    "You know something that would really make me applaud? A guy gets stuck in quicksand, then sinks, then suddenly comes shooting out, riding on water skis! How do they do that?!",
    "Here's a good thing to do if you go to a party and you don't know anybody: First, take out the garbage. Then go around and collect any extra garbage that people might have, like a crumpled-up napkin, and take that out too. Pretty soon people will want to meet the busy garbage guy.",
    "How come the dove gets to be the peace symbol? How about the pillow? It has more feathers than the dove, and it doesn't have that dangerous beak.",
    "Somebody told me it was frightening how much topsoil we are losing each year, but I told that story around the campfire and nobody got scared.",
    "One day one of my little nephews came up to me and asked me if the equator was a real line that went around the Earth, or just an imaginary one. I had to laugh. Laugh and laugh. Because I didn't know, and I thought that maybe by laughing he would forget what he asked me.",
    "Even though he was an enemy of mine, I had to admit that what he had accomplished was a brilliant piece of strategy. First, he punched me, then he kicked me, then he punched me again.",
    "If I come back as an animal in my next lifetime, I hope it's some type of parasite, because this is the part where I take it EASY!",
    "I bet the main reason the police keep people away from a plane crash is they don't want anybody walking in and lying down in the crash stuff, then when somebody comes up act like they just woke up and go, \"What was THAT?!\"",
    "Sometimes I think you have to march right in and demand your rights, even if you don't know what your rights are, or who the person is you're talking to. Then, on the way out, slam the door.",
    "If you ever crawl inside an old hollow log and go to sleep, and while you're in there some guys come and seal up both ends and then put it on a truck and take it to another city, boy, I don't know what to tell you.",
    "What is it that makes a complete stranger dive into an icy river to save a solid-gold baby? Maybe we'll never know. ",
    "If you're in a boxing match, try not to let the other guy's glove touch your lips, because you don't know where that glove has been.",
    "If your friend is already dead, and being eaten by vultures, I think it's okay to feed some bits of your friend to one of the vultures, to teach him to do some tricks. But ONLY if you're serious about adopting the vulture.",
    "If you're an archaeologist, I bet it's real embarrassing to put together a skull from a bunch of ancient bone fragments, but then it turns out it's not a skull but just an old dried-out potato.",
    "To me, clowns aren't funny. In fact, they're kinda scary. I've wondered where this started, and I think it goes back to the time I went to the circus and a clown killed my dad.",
    "I guess the hard thing for a lot of people to accept is why God would allow me to go running through their yards, yelling and spinning around.",
    "Whenever I need to ``get away,'' I just get away in my mind. I go to my imaginary spot, where the beach is perfect and the water is perfect and the weather is perfect. The only bad thing there are the flies. They're terrible!",
    "Whenever someone asks me to define love, I usually think for a minute, then I spin around and pin the guy's arm behind his back. NOW who's asking the questions?",
    "Most of the time it was probably real bad being stuck down in a dungeon. But some days, when there was a bad storm outside, you'd look out your little window and think, ``Boy, I'm glad I'm not out in THAT.''",
    "If you ever reach total enlightenment while you're drinking a beer, I bet it makes beer shoot out your nose. ",
    "I think a good gift for the president would be a chocolate revolver. And since he's so busy, you'd probably have to run up to him and hand it to him.",
    "There are many stages to a man's life. In the first stage, he is young and eager, like a beaver. In the second stage, he wants to build things, like dams, and maybe chew down some trees. In the third stage, he feels trapped, and then ``skinned.'' I'm not sure what the fourth stage is.",
    "For mad scientists who keep brains in jars, here's a tip: Why not add a slice of lemon to each jar, for freshness.",
    "Can't the Marx Brothers be arrested and maybe even tortured for all the confusion and problems they've caused?",
    "Ambition is like a frog sitting on a Venus's-flytrap. The flytrap can bite and bite, but it won't bother the frog because it only has little tiny plant teeth. But some other stuff could happen and it could be like ambition.",
    "After I die, wherever my spirit goes, I'm going to try to get back and visit my skeleton at least once a year, because, \"Hey, old buddy, how's it going?\"",
    "When the age of the Vikings came to a close, they must have sensed it. Probably, they gathered together one evening, slapped each other on the back and said, \"Hey, good job.\"",
    "I think a new, different kind of bowling should be \"carpet bowling.\" It's just like regular bowling, only the lanes are carpet instead of wood. I don't know why we should do this, but my God, we've got to try something!",
    "I'd like to see a nature film where an eagle swoops down and pulls a fish out of a lake, and then maybe he's flying along, low to the ground, and the fish pulls a worm out of the ground. Now that's a documentary!",
    "Whether they ever find life there or not, I think Jupiter should be considered an enemy planet.",
    "If you think a weakness can be turned into a strength, I hate to tell you this, but that's another weakness.",
    "If you ever fall off the Sears Tower, just go real limp, because maybe you'll look like a dummy and people will try to catch you because, hey, free dummy.",
    "I think the mistake a lot of us make is thinking the state-appointed psychiatrist is our \"friend.\" ",
    "Instead of putting a quarter under a kid's pillow, how about a pinecone? That way, he learns that \"wishing\" isn't going to save our national forests.",
    "If you go parachuting, and your parachute doesn't open, and your friends are all watching you fall, I think a funny gag would be to pretend you were swimming.",
    "It's interesting to think that my ancestors used to live in the trees, like apes, until finally they got the nerve to head out onto the plains, where some were probably hit by cars.",
    "I remember one day I was at Grandpa's farm and I asked him about sex. He sort of smiled and said, \"Maybe instead of telling you what sex is, why don't we go out to the horse pasture and I'll show you.\" So we did, and there on the ground were my parents having sex.",
    "If you ever feel like you're on the verge of a nervous breakdown, just follow these simple rules: First, calm down; second, come over and wash my car; third, shine all my shoes. There, isn't that better?",
    "You know what would make a good story? Something about a clown who makes people happy, but inside he's real sad. Also, he has severe diarrhea.",
    "It's probably not a good idea to be chewing on a toothpick if you're talking to the president, because what if he tells a funny joke and you laugh so hard you spit the toothpick out and it hits him in the face or something.",
    "You know what would be the most terrifying thing that could ever happen to a flea? Getting caught inside a watch somehow. You don't even care, do you.",
    "Some folks say it was a miracle. Saint Francis suddenly appeared and knocked the next pitch clean over the fence. But I think it was just a lucky swing.",
    "When this girl at the museum asked me who I liked better, Monet or Manet, I said, \"I like mayonnaise.\" She just stared at me, so I said it again, louder. Then she left. I guess she went to try to find some mayonnaise for me.",
    "Despair is like a cable that is buried just under the surface of the ground. You pull it up and pull it up, but that cable just keeps right on going, clear across a field, until you come to a bunch of guys who are burying the cable. Then just walk up to them and go, \"Hey, have you seen Fred?\" And they'll say, \"Fred who?\" And you say, \"Fred of snakes?\" Then cover your ears, because big laughs are coming.",
    "The face of a child can say it all, especially the mouth part of the face.",
    "Why do the caterpillar and the ant have to be enemies? One eats leaves, and the other eats caterpillars. Oh, I see now.",
    "Just as bees will swarm about to protect their nest, so will I \"swarm about\" to protect my nest of chocolate eggs. ",
    "If a kid asks where rain comes from, I think a cute thing to tell him is \"God is crying.\" And if he asks why God is crying, another cute thing to tell him is \"Probably because of something you did.\"",
    "If any man says he hates war more than I do, he better have a knife, that's all I have to say.",
    "I bet one legend that keeps recurring throughout history, in every culture, is the story of Popeye.",
    "To me, truth is not some vague, foggy notion. Truth is real. And, at the same time, unreal. Fiction and fact and everything in between, plus some things I can't remember, all rolled into one big \"thing.\" This is truth, to me.",
    "A good way to keep a mob of peasants from killing your monster is when they break into your castle, make them be real quiet, then open a door and there's the monster, sound asleep.",
    "Consider the daffodil. And while you're doing that, I'll be over here, looking through your stuff.",
    "If you're a circus clown, and you have a dog that you use in your act, I don't think it's a good idea to also dress the dog up like a clown, because people see that and they think, \"Forgive me, but that's just too much.\"",
    "I think a cute movie idea would be about a parrot who is raised by eagles. It would be cute because the parrot can't seem to act like an eagle. After a while, though, to keep the movie from getting boring, maybe put in some pornography. Later, we see the happy parrot flying along, acting like an eagle. He see two parrots below and starts to attack, but it's his parents. Then, some more pornography.",
    "Today I accidentally stepped on a snail on the sidewalk in front of our house. And I thought, I too am like that snail. I build a defensive wall around myself, a \"shell\" if you will. But my shell isn't made out of a hard, protective substance. Mine is made out of tinfoil and paper bags.",
    "I think somebody should come up with a way to breed a very large shrimp. That way, you could ride him, then after you camped at night, you could eat him. How about it, science?",
    "I wish everybody would have to have an electric thing implanted in our heads that gave us a shock whenever we did something to disobey the president. Then somehow I get myself elected president.",
    "I remember when I was in the army, we had the toughest drill sergeant in the world. He'd get right up next to your face and yell, and if you didn't have the right answers, mister, you'd be peeling potatoes or changing the latrine. Hey, wait. I wasn't in the army. Then who WAS that guy?!",
    "If you're ever selling your house, and some people come by, and a big rat comes out and he's dragging the rattrap because it didn't quite kill him, just tell the people he's your pet and that's a trick you taught him.",
    "Instead of trying to build newer and bigger weapons of destruction, mankind should be thinking about getting more use out of the weapons we already have.",
    "I don't think I'm ever more \"aware\" than I am right after I hit my thumb with a hammer.",
    "Worship the potato? The idea seemed silly to me. But then I thought, what else is more deserving of worship? It's simple, it comes from the earth, and it can kill you if you disobey it.",
    "Sometimes when I feel like killing someone, I do a little trick to calm myself down. I'll go over to the person's house and ring the doorbell. When the person comes to the door, I'm gone, but you know what I've left on the porch? A jack-o'-lantern with a knife in the side of its head with a note that says \"You.\" After that, I usually feel a lot better, and no harm done.",
    "Happiness is not a circus clown rolling around in a big tractor tire so that his arms and legs form \"spokes.\" Happiness is when he stops.",
    "If you're traveling in a time machine, and you're eating corn on the cob, I don't think it's going to affect things one way or the other. But here's the point I'm trying to make: Corn on the cob is good, isn't it.",
    "The memories of my family outings are still a source of strength to me. I remember we'd all pile into the car---I forget what kind it was---and drive and drive. I'm not sure where we'd go, but I think there were some trees there. The smell of something was strong in the air as we played whatever sport we played. I remember a bigger, older guy we called \"Dad.\" We'd eat some stuff, or not, and then I think we went home. I guess some things never leave you.",
    "In weightlifting, I don't think sudden, uncontrolled urination should automatically disqualify you.",
    "I bet a funny thing about driving a car off a cliff is, while you're in midair, you still hit those brakes! Hey, better try the emergency brake!",
    "You know what's probably a good thing to hang on your porch in the summertime, to keep mosquitoes away from you and your guests? Just a big bag of blood.",
    "Here's a good joke to do during an earthquake: Straddle a big crack in the ground, and if it opens wider, go \"Whoa! Whoa!\" and flail your arms around, like you're going to fall in.",
    "To me, there's no better symbol for the world than a grasshopper lying dead on a gravel road, and maybe there's a globe lying next to him.",
    "I wish scientists would come up with a way to make dogs a lot bigger, but with a smaller head. That way, they'd still be good as watchdogs, but they wouldn't eat so much.",
    "To us, it might look like just a rag. But to the brave, embattled men of the fort, it was more than that. It was a flag of surrender. And after that, it was torn up and used for shoe-shine rags, so the men would look nice for the surrender.",
    "If you ever go temporarily insane, don't shoot somebody, like a lot of people do. Instead, try to get some weeding done, because you'd really be surprised.",
    "When you die, if you go somewhere where they ask you a bunch of questions about your life and what you learned and all, I think a good way to get out of it is just to say, \"No speaka English.\" ",
    "I wish I could shrink down to the size of an ant. And maybe there would be thousands of other people shrunken down to ant-size, and we would get together and dig tunnels down into the ground and live there. But don't ever call us \"ants,\" because we hate that.",
    "If you work on a lobster boat, sneaking up behind someone and pinching him is probably a joke that gets old real fast.",
    "Laurie got offended that I used the word \"puke.\" But to me, that's what her dinner tasted like.",
    "The first thing was, I learned to forgive my Then, I told myself, \"Go ahead and do whatever you want, it's okay by me.\"",
    "If I ever become a mummy, I'm going to have it so when somebody opens my lid, a boxing glove on a spring shoots out.",
    "I hope they never find out that lightning has a lot of vitamins in it, because do you hide from it or not?",
    "The wise man can pick up a grain of sand and envision a whole universe. But the stupid man will just lie down on some seaweed and roll around until he's completely draped in it. Then he'll stand up and go, \"Hey, I'm Vine Man.\"",
    "If I come back as a horsefly, I think my favorite thing would be to land on someone's lip. Even if they smash you, ick!, you're all over their lip!",
    "If you had a school for professional fireworks people, I don't think you could cover fuses in just one class. It's just too rich a subject.",
    "When people say that the desert is lifeless, it just makes me want to grab them by the collar and yell, \"Why you stupid, stupid bastard!\" Then I drive them out into the desert to where the circus is, and point out the many forms of zebra and clown life.",
    "If you were a pirate, you know what would be the one thing that would really make you mad? Treasure chests with no handles. How the hell are you supposed to carry it?!",
    "When you go to a party at somebody's house, don't automatically assume that the drinks are free. Ask, and ask often.",
    "People laugh when I say that I think a jellyfish is one of the most beautiful things in the world. What they don't understand is, I mean a jellyfish with long, blond hair.",
    "Like jewels in a crown, the precious stones glittered in the queen's round metal hat.",
    "Broken promises don't upset me. I just think, why did they believe me?",
    "I'd rather be rich than stupid.",
    "If you were a poor Indian with no weapons, and a bunch of conquistadors came up to you and asked where the gold was, I don't think it would be a good idea to say, \"I swallowed it. So sue me.\" ",
    "I wish outer-space guys would conquer Earth and make people their pets, because I'd like to have one of those little basket-beds with my name on it.",
    "I wish I would have a real tragic love affair and get so bummed out that I'd just quit my job and become a bum for a few years, because I was thinking about doing that anyway.",
    "When you first start wearing a turban, probably the most common mistake is wrapping it too tight. You have to allow the head to breathe.",
    "People just naturally assume that dogs would be incapable of working together on some sort of construction project. But what about just a big field full of holes?",
    "One thing kids like is to be tricked. For instance, I was going to take my little nephew to Disneyland, but instead I drove him to an old burned-out warehouse. \"Oh, no,\" I said, \"Disneyland burned down.\" He cried and cried, but I think that deep down, he thought it was a pretty good joke. I started to drive over to the real Disneyland, but it was getting pretty late.",
    "If you get invited to your first orgy, don't just show up nude. That's a common mistake. You have to let nudity \"happen.\"",
    "Sometimes I think I'd be better off dead. No, wait. Not me, you.",
    "If life deals you lemons, why not go kill someone with the lemons (maybe by shoving them down his throat)?",
    "I wouldn't be surprised if someday some fishermen caught a big shark and cut it open, and there inside was a whole person. Then they cut the person open, and in him is a little baby shark. And in the baby shark there isn't a person, because it would be too small. But there's a little doll or something, like a Johnny Combat little toy guy---something like that.",
    "To me, boxing is like a ballet, except there's no music, no choreography, and the dancers hit each other.",
    "During the Middle Ages, probably one of the biggest mistakes was not putting on your armor because you were \"just going down to the corner.\"",
    "If I was being executed by injection, I'd clean up my cell real neat. Then, when they came to get me, I'd say, \"Injection? I thought you said `inspection'.\" They'd probably feel real bad, and maybe I could get out of it. ",
    "Higher beings from outer space may not want to tell us the secrets of life, because we're not ready. But maybe they'll change their tune after a little torture.",
    "As I bit into the nectarine, it had a crisp juiciness about it that was very pleasurable---until I realized it wasn't a nectarine at all, but A HUMAN HEAD!!",
    "Sometimes I think the so-called experts actually ARE experts.",
    "If you're a young Mafia gangster out on your first date, I bet it's really embarrassing if someone tries to kill you.",
    "If trees could scream, would we be so cavalier about cutting them down? We might, if they screamed all the time, for no good reason.",
    "If you're robbing a bank, and your pants suddenly fall down, I think it's okay to laugh, and to let the hostages laugh too, because come on, life is funny.",
    "When I found the skull in the woods, the first thing I did was call the police. But then I got curious about it. I picked it up, and started wondering who this person was, and why he had deer horns.",
    "Let's be honest: Isn't a lot of what we call tap dancing really just nerves?",
    "I wish I had a dollar for every time I spent a dollar, because then, yahoo!, I'd have all my money back.",
    "If the Vikings were around today, they would probably be amazed at how much glow-in-the-dark stuff we have, and how we take so much of it for granted.",
    "If you want to sue somebody, just get a little plastic skeleton and lay it in their yard. Then tell them their ants ate your baby.",
    "Contrary to popular belief, the most dangerous animal is not the lion or tiger or even the elephant. The most dangerous animal is a shark riding on an elephant, just trampling and eating everything they see.",
    "Love is not something that you can put chains on and throw into a lake. That's called Houdini. Love is liking someone a lot.",
    "We used to laugh at Grandpa when he'd head off to go fishing. But we wouldn't be laughing that evening, when he'd come back with some whore he picked up in town.",
    "Of all the warning sounds that animals make, I think the one that's the least effective on me is a kind of clicking noise.",
    "Probably to a shark, about the funniest thing there is is a wounded seal, trying to swim to shore, because WHERE DOES HE THINK HE'S GOING?!",
    "We tend to scoff at the beliefs of the ancients. But we can't scoff at them personally, to their faces, and this is what annoys me.",
    "I bet when they weren't fighting, Vikings with horn helmets had to stick potatoes on the ends of the horns, so as to avoid eye pokings to fellow Vikings and lady Vikings.",
    "The other day I got out my can opener and was opening a can of worms when I thought, \"What am I doing?!\"",
    "What am I afraid of? I'll tell you: a feather. that's right, a feather. How could anyone be afraid of a feather, you say. That's an honest question, and I'll try to give it an honest answer. First of all, did I say it was a poison feather?",
    "I'm telling you, just attach a big parachute TO THE PLANE ITSELF! Is anyone listening to me?!",
    "I guess of all my uncles, I liked Uncle Cave Man the best. We called him Uncle Cave Man because he lived in a cave and because sometimes he'd eat one of us. Later on we found out he was a bear.",
    "Isn't it funny how one minute life can be such a struggle, and the next minute you're just driving real fast, swerving back and forth across the road?",
    "Fear can sometimes be a useful emotion. For instance, let's say you're an astronaut on the moon and you fear that your partner has been turned into",
    "Dracula. The next time he goes out for the moon pieces, wham!, you just slam the door behind him and blast off. He might call you on the radio and say he's not Dracula, but you just say, \"Think again, bat man.\"",
    "Sometimes I wonder if I'm patriotic enough. Yes, I want to kill people, but on both sides.",
    "It makes me mad when people say I turned and ran like a scared rabbit. Maybe it was like an angry rabbit, who was going to fight in another fight, away from the first fight.",
    "I think in one of my previous lives I was a mighty king, because I like people to do what I say.",
    "It's funny that pirates were always going around searching for treasure, and they never realized that the real treasure was the fond memories they were creating.",
    "I don't think God put me on this planet to judge others. I think he put me on this planet to gather specimens and take them back to my home planet.",
    "If aliens from outer space ever come and we show them our civilization and they make fun of it, we should say we were just kidding, that this isn't really our civilization, but a gag we hoped they would like. Then we tell them to come back in twenty years to see our REAL civilization. After that, we start a crash program of coming up with an impressive new civilization. Either that, or just shoot down the aliens as they're waving good-bye.",
    "The tiger can't change his spots. No, wait, he did! Good for him!",
    "I'd like to see a nude opera, because when they hit those high notes I bet you can really see it in those genitals.",
    "If the captain invited me to his party, after he had whipped me earlier in the day, up on deck, I guess I'd go, but I'd try to find some excuse to leave early.",
    "If you ever catch on fire, try to avoid seeing yourself in the mirror, because I bet that's what REALLY throws you into a panic.",
    "Sometimes the beauty of the world is so overwhelming, I just want to throw back my head and gargle. Just gargle and gargle, and I don't care who hears me, because I am beautiful.",
    "If you go to a costume party at your boss's house, wouldn't you think a good costume would be to dress up like the boss's wife? Trust me, it's not.",
    "It's not good to let any kid near a container that has a skull and crossbones on it, because there might be a skeleton costume inside and the kid could put it on and really scare you.",
    "One thing vampire children have to be taught early on is, don't run with a wooden stake.",
    "It takes a big man to cry, but it takes a bigger man to laugh at that man.",
    "If you ever drop your keys into a river of molten lava, let 'em go, because, man, they're gone.",
    "I can't stand cheap people. It makes me real mad when someone says something like \"Hey, when are you going to pay me that hundred dollars you owe me?\" or \"Do you have that fifty dollars you borrowed?\" Man, quit being so cheap!",
    "I wish a robot would get elected President. That way, when he came to town, we could all take a shot at him and not feel too bad.",
    "If you ever discover that what you're seeing is a play within a play, just slow down, take a deep breath, and hold on for the ride of your life.",
    "Better not take a dog on the space shuttle, because if he sticks his head out when you're coming home, his face might burn up.",
    "I think one way police departments could make some money would be to hold a yard sale of murder weapons. Many people, for example, could probably use a cheap ice pick.",
    "If you're in a war, instead of throwing a hand grenade at some guys, throw one of those little baby-type pumpkins. Maybe it'll make everyone think of how crazy war is, and while they're thinking, you can throw a real grenade.",
    "I think someone should have had the decency to tell me the luncheon was free. To make someone run out with potato salad in his hand, pretending that he's throwing up, is not what I call hospitality.",
    "I bet what happened was, they discovered fire and invented the wheel on the same day. Then, that night, they burned the wheel.",
    "Here's a suggestion for a new animal, if some new ones get created or evolve: something that stings you, then laughs at you.",
    "I think a good movie would be about a guy who's a brain scientist, but he gets hit on the head and it damages the part of the brain that makes you want to study the brain.",
    "If you're pretty happy, but you have a little Chihuahua that's always biting you on the ankles, still that's pretty good isn't it? I'm going to go ahead and keep you in the \"happy\" category.",
    "If I could be a bird, I think I'd be a penguin, because then I could walk around on two feet with a lot of other guys like me.",
    "Don't ever get your speedometer confused with your clock, like I did once, because the faster you go, the later you think you are.",
    "Sometimes I think the world has gone completely mad. And then I think, \"Aw, who cares?\" And then I think, \"Hey, what's for supper?\"",
    "I don't say that the bird is \"good\" or the bat is \"bad.\" But I will say this: At least the bird is less nude.",
    "If you define cowardice as running away at the first sign of danger, screaming and tripping and begging for mercy, then yes, Mister Brave Man, I guess I am a coward.",
    "One thing a computer can do that most humans can't is be sealed up in a cardboard box and sit in a warehouse.",
    "If you want to be the popular one at a party, here's a good thing to do: Go up to some people who are talking and laughing and say, \"Well, technically that's illegal.\" It might fit in with what somebody just said. And even if it doesn't, so what, I hate this stupid party.",
    "You know how to paint a room real fast? Just put paint rollers on your feet and somehow figure out how to skate up the walls and across the ceiling.",
    "I guess one of the funniest memories of my grandfather was the time I was at his house and that tied-up man with the gag in his mouth came hopping out of the closet and started yelling that HE was really my grandfather and the other guy was an imposter and to run for help. Who was that guy?! Oh, well, never saw HIM again.",
    "You know what makes good hair for a snow man? REAL hair. Don't ask me why, but it works.",
    "I hope if dogs ever take over the world, and they choose a king, they don't just go by size, because I bet there are some Chihuahuas with some good ideas.",
    "Most people don't realize that large pieces of coral, which have been painted brown and attached to the skull by common wood screws, can make a child look like a deer.",
    "When you're going up the stairs and you take a step, kick the other leg up high behind you to keep people from following too close.",
    "If you ever have to steal money from your kid, and later on he discovers it's gone, I think a good thing to do is to blame it on Santa Claus.",
    "I think Superman and Santa Claus are actually the same guy, and I'll tell you why: Both fly, both wear red, and both have a beard.",
    "Whether they live in an igloo or a grass shack or a mud hut, people around the world all want the same thing: a better house!",
    "Blow ye winds, like the trumpet blows; but without that noise.",
    "When I think back on all the blessings I have been given in my life, I can't think of a single one, unless you count that rattlesnake that granted me all those wishes.",
  ]
end
