name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7' ]
    name: Lint & Test with Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Prerequisites
        run: |
          sudo apt-get install libsqlite3-dev
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup Ruby environment
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Testing & Linting
        run: bundle exec rake
